repository: letbingo/3s_navi.github.io
repository_url: https://github.com/letbingo/3s_navi.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: 遥感地信导航 · 3S-Navi
alias_en: 3S-Navi
alias_cn: 遥感地信导航
description: A Navigation Website for BYR
keywords: 遥感地信导航, GNSS, GIS, GS, Navi, Navigation
url: https://letbingo.github.io/3s_navi.github.io/
established_at: "2023-09-18T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /3s_navi.github.io/images/logo.png
logo: /3s_navi.github.io/images/logo.png
logo_dark: /3s_navi.github.io/images/logo-dark.svg
logo_white: /3s_navi.github.io/images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor